install.packages(c('shiny'), repos='http://cran.rstudio.com/')
install.packages(c('rmarkdown'), repos='http://cran.rstudio.com/')
install.packages(c('flexdashboard'), repos='http://cran.rstudio.com/')
install.packages(c('dplyr'), repos='http://cran.rstudio.com/')
install.packages(c('ggplot2'), repos='http://cran.rstudio.com/')
install.packages(c('tidyr'), repos='http://cran.rstudio.com/')
install.packages(c('reshape2'), repos='http://cran.rstudio.com/')
install.packages(c('plotly'), repos='http://cran.rstudio.com/')
install.packages(c('DT'), repos='http://cran.rstudio.com/')
install.packages(c('tidyverse'), repos='http://cran.rstudio.com/')
install.packages(c('knitr'), repos='http://cran.rstudio.com/')
install.packages('rgeos', type='source')
install.packages('rgdal', type='source')
install.packages(c('tidycensus'), repos='http://cran.rstudio.com/')
install.packages(c('maptool'), repos='http://cran.rstudio.com/')
install.packages(c('tigris'), repos='http://cran.rstudio.com/')
install.packages(c('censusapi'), repos='http://cran.rstudio.com/')
install.packages(c('ggmap'), repos='http://cran.rstudio.com/')
install.packages(c('viridis'), repos='http://cran.rstudio.com/')
install.packages(c('foreign'), repos='http://cran.rstudio.com/')
install.packages(c('leaflet'), repos='http://cran.rstudio.com/')
install.packages(c('shinycssloaders'), repos='http://cran.rstudio.com/')
install.packages(c('stringr'), repos='http://cran.rstudio.com/')
install.packages(c('lubridate'), repos='http://cran.rstudio.com/')
install.packages(c('RMySQL'), repos='http://cran.rstudio.com/')
install.packages(c('dbplyr'), repos='http://cran.rstudio.com/')
install.packages(c('viridis'), repos='http://cran.rstudio.com/')
install.packages(c('forcats'), repos='http://cran.rstudio.com/')
install.packages(c('zoo'), repos='http://cran.rstudio.com/')
install.packages(c('sf'), repos='http://cran.rstudio.com/')
install.packages(c('shinythemes'), repos='http://cran.rstudio.com/')
install.packages(c('shinyWidgets'), repos='http://cran.rstudio.com/')
install.packages(c('jsonlite'), repos='http://cran.rstudio.com/')
install.packages(c('devtools'), repos='http://cran.rstudio.com/')
install.packages(c('tuber'), repos='http://cran.rstudio.com/')
install.packages(c('googleAuthR'), repos='http://cran.rstudio.com/')
install.packages(c('readxl'), repos='http://cran.rstudio.com/')


devtools::install_github("opensci/tabulizerjars")
devtools::install_github("opensci/tabulizer")

#if (!require("ghit")) {
#    install.packages("ghit")
#}
# on 64-bit Windows
#ghit::install_github(c("ropensci/tabulizerjars", "ropensci/tabulizer"), INSTALL_opts = "--no-multiarch")
# elsewhere
#ghit::install_github(c("ropensci/tabulizerjars", "ropensci/tabulizer"))
install.packages(c('data.table'), repos='http://cran.rstudio.com/')
install.packages(c('rhandsontable'), repos='http://cran.rstudio.com/')
install.packages(c('shinyjs'), repos='http://cran.rstudio.com/')
install.packages(c('shinyBS'), repos='http://cran.rstudio.com/')
install.packages(c('png'), repos='http://cran.rstudio.com/')
install.packages(c('data.table'), repos='http://cran.rstudio.com/')

